### ISSUE TITLE
Directory listing when index.html is not found

### ISSUE THREAD

**Issue by silviubogan** [IonicaBizau/statique#59]
I suggest that the executable `/bin/statique` of the Statique web server should show a directory listing when a file named `index.html` is not found in the requested directory path.

By searching "apache directory listing" on Google I found this example image:

![apache-crude-directory-listing](https://user-images.githubusercontent.com/198924/31951460-dc156d86-b8e6-11e7-8174-6bfe14d76902.png)

Can I start working on this?

**Comment by IonicaBizau** [comment]
I'm not for this, there are other tools doing that. I want to keep Statique relatively small.
